// This file was automatically generated.  Do not modify.

"use strict";

goog.provide("Blockly.ScratchMsgs.allLocales");

goog.require("Blockly.ScratchMsgs");

Blockly.ScratchMsgs.locales["en"] = {
  CONTROL_FOREVER: "forever Loop",
  CONTROL_REPEAT: "repeat %1",
  CONTROL_IF: "if %1 then",
  CONTROL_ELSE: "else",
  CONTROL_STOP: "stop",
  CONTROL_STOP_ALL: "all",
  CONTROL_STOP_THIS: "this script",
  CONTROL_STOP_OTHER: "other scripts in sprite",
  CONTROL_WAIT: "wait %1 seconds",
  CONTROL_WAITUNTIL: "wait until %1",
  CONTROL_REPEATUNTIL: "repeat until %1",
  CONTROL_WHILE: "while %1",
  CONTROL_FOREACH: "for each %1 in %2",
  CONTROL_STARTASCLONE: "when I start as a clone",
  CONTROL_CREATECLONEOF: "create clone of %1",
  CONTROL_CREATECLONEOF_MYSELF: "myself",
  CONTROL_DELETETHISCLONE: "delete this clone",
  CONTROL_COUNTER: "counter",
  CONTROL_INCRCOUNTER: "increment counter",
  CONTROL_CLEARCOUNTER: "clear counter",
  CONTROL_ALLATONCE: "all at once",
  DATA_SETVARIABLETO: "set %1 to %2",
  DATA_CHANGEVARIABLEBY: "change %1 by %2",
  DATA_SHOWVARIABLE: "show variable %1",
  DATA_HIDEVARIABLE: "hide variable %1",
  DATA_ADDTOLIST: "add %1 to %2",
  DATA_DELETEOFLIST: "delete %1 of %2",
  DATA_DELETEALLOFLIST: "delete all of %1",
  DATA_INSERTATLIST: "insert %1 at %2 of %3",
  DATA_REPLACEITEMOFLIST: "replace item %1 of %2 with %3",
  DATA_ITEMOFLIST: "item %1 of %2",
  DATA_ITEMNUMOFLIST: "item # of %1 in %2",
  DATA_LENGTHOFLIST: "length of %1",
  DATA_LISTCONTAINSITEM: "%1 contains %2?",
  DATA_SHOWLIST: "show list %1",
  DATA_HIDELIST: "hide list %1",
  DATA_INDEX_ALL: "all",
  DATA_INDEX_LAST: "last",
  DATA_INDEX_RANDOM: "random",
  EVENT_WHENARDUINOBEGIN: "when Arduino begin",
  EVENT_WHENMICROPYTHONBEGIN: "when MicroPython begin",
  EVENT_WHENMICROBITBEGIN: "when Microbit begin",
  EVENT_WHENMICROBITBUTTONPRESSED: "when button %1 pressed",
  EVENT_WHENMICROBITPINBEINGTOUCHED: "when pin %1 being touched",
  EVENT_WHENMICROBITGESTURE: "when the gestrue %1",
  EVENT_WHENFLAGCLICKED: "when %1 clicked",
  EVENT_WHENTHISSPRITECLICKED: "when this sprite clicked",
  EVENT_WHENSTAGECLICKED: "when stage clicked",
  EVENT_WHENTOUCHINGOBJECT: "when this sprite touches %1",
  EVENT_WHENBROADCASTRECEIVED: "when I receive %1",
  EVENT_WHENBACKDROPSWITCHESTO: "when backdrop switches to %1",
  EVENT_WHENGREATERTHAN: "when %1 > %2",
  EVENT_WHENGREATERTHAN_TIMER: "timer",
  EVENT_WHENGREATERTHAN_LOUDNESS: "loudness",
  EVENT_BROADCAST: "broadcast %1",
  EVENT_BROADCASTANDWAIT: "broadcast %1 and wait",
  EVENT_WHENKEYPRESSED: "when %1 key pressed",
  EVENT_WHENMICROBITGESTURE_SHAKEN: "shaken",
  EVENT_WHENMICROBITGESTURE_TILTEDUPWARD: "tilted upward",
  EVENT_WHENMICROBITGESTURE_TILTEDDOWNWARD: "tilted downward",
  EVENT_WHENMICROBITGESTURE_TILTEDDLEFTWARD: "tilted leftward",
  EVENT_WHENMICROBITGESTURE_TILTEDDRIGHTWARD: "tilted rightward",
  EVENT_WHENMICROBITGESTURE_FACEUP: "face up",
  EVENT_WHENMICROBITGESTURE_FACEDOWN: "face down",
  EVENT_WHENMICROBITGESTURE_FREEFALL: "freefall",
  EVENT_WHENKEYPRESSED_SPACE: "space",
  EVENT_WHENKEYPRESSED_LEFT: "left arrow",
  EVENT_WHENKEYPRESSED_RIGHT: "right arrow",
  EVENT_WHENKEYPRESSED_DOWN: "down arrow",
  EVENT_WHENKEYPRESSED_UP: "up arrow",
  EVENT_WHENKEYPRESSED_ANY: "any",
  LOOKS_SAYFORSECS: "say %1 for %2 seconds",
  LOOKS_SAY: "say %1",
  LOOKS_HELLO: "Hello!",
  LOOKS_THINKFORSECS: "think %1 for %2 seconds",
  LOOKS_THINK: "think %1",
  LOOKS_HMM: "Hmm...",
  LOOKS_SHOW: "show",
  LOOKS_HIDE: "hide",
  LOOKS_HIDEALLSPRITES: "hide all sprites",
  LOOKS_EFFECT_COLOR: "color",
  LOOKS_EFFECT_FISHEYE: "fisheye",
  LOOKS_EFFECT_WHIRL: "whirl",
  LOOKS_EFFECT_PIXELATE: "pixelate",
  LOOKS_EFFECT_MOSAIC: "mosaic",
  LOOKS_EFFECT_BRIGHTNESS: "brightness",
  LOOKS_EFFECT_GHOST: "ghost",
  LOOKS_CHANGEEFFECTBY: "change %1 effect by %2",
  LOOKS_SETEFFECTTO: "set %1 effect to %2",
  LOOKS_CLEARGRAPHICEFFECTS: "clear graphic effects",
  LOOKS_CHANGESIZEBY: "change size by %1",
  LOOKS_SETSIZETO: "set size to %1 %",
  LOOKS_SIZE: "size",
  LOOKS_CHANGESTRETCHBY: "change stretch by %1",
  LOOKS_SETSTRETCHTO: "set stretch to %1 %",
  LOOKS_SWITCHCOSTUMETO: "switch costume to %1",
  LOOKS_NEXTCOSTUME: "next costume",
  LOOKS_SWITCHBACKDROPTO: "switch backdrop to %1",
  LOOKS_GOTOFRONTBACK: "go to %1 layer",
  LOOKS_GOTOFRONTBACK_FRONT: "front",
  LOOKS_GOTOFRONTBACK_BACK: "back",
  LOOKS_GOFORWARDBACKWARDLAYERS: "go %1 %2 layers",
  LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "forward",
  LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "backward",
  LOOKS_BACKDROPNUMBERNAME: "backdrop %1",
  LOOKS_COSTUMENUMBERNAME: "costume %1",
  LOOKS_NUMBERNAME_NUMBER: "number",
  LOOKS_NUMBERNAME_NAME: "name",
  LOOKS_SWITCHBACKDROPTOANDWAIT: "switch backdrop to %1 and wait",
  LOOKS_NEXTBACKDROP_BLOCK: "next backdrop",
  LOOKS_NEXTBACKDROP: "next backdrop",
  LOOKS_PREVIOUSBACKDROP: "previous backdrop",
  LOOKS_RANDOMBACKDROP: "random backdrop",
  MOTION_MOVESTEPS: "move %1 steps",
  MOTION_TURNLEFT: "turn %1 %2 degrees",
  MOTION_TURNRIGHT: "turn %1 %2 degrees",
  MOTION_POINTINDIRECTION: "point in direction %1",
  MOTION_POINTTOWARDS: "point towards %1",
  MOTION_POINTTOWARDS_POINTER: "mouse-pointer",
  MOTION_POINTTOWARDS_RANDOM: "random direction",
  MOTION_GOTO: "go to %1",
  MOTION_GOTO_POINTER: "mouse-pointer",
  MOTION_GOTO_RANDOM: "random position",
  MOTION_GOTOXY: "go to x: %1 y: %2",
  MOTION_GLIDESECSTOXY: "glide %1 secs to x: %2 y: %3",
  MOTION_GLIDETO: "glide %1 secs to %2",
  MOTION_GLIDETO_POINTER: "mouse-pointer",
  MOTION_GLIDETO_RANDOM: "random position",
  MOTION_CHANGEXBY: "change x by %1",
  MOTION_SETX: "set x to %1",
  MOTION_CHANGEYBY: "change y by %1",
  MOTION_SETY: "set y to %1",
  MOTION_IFONEDGEBOUNCE: "if on edge, bounce",
  MOTION_SETROTATIONSTYLE: "set rotation style %1",
  MOTION_SETROTATIONSTYLE_LEFTRIGHT: "left-right",
  MOTION_SETROTATIONSTYLE_DONTROTATE: "don't rotate",
  MOTION_SETROTATIONSTYLE_ALLAROUND: "all around",
  MOTION_XPOSITION: "x position",
  MOTION_YPOSITION: "y position",
  MOTION_DIRECTION: "direction",
  MOTION_SCROLLRIGHT: "scroll right %1",
  MOTION_SCROLLUP: "scroll up %1",
  MOTION_ALIGNSCENE: "align scene %1",
  MOTION_ALIGNSCENE_BOTTOMLEFT: "bottom-left",
  MOTION_ALIGNSCENE_BOTTOMRIGHT: "bottom-right",
  MOTION_ALIGNSCENE_MIDDLE: "middle",
  MOTION_ALIGNSCENE_TOPLEFT: "top-left",
  MOTION_ALIGNSCENE_TOPRIGHT: "top-right",
  MOTION_XSCROLL: "x scroll",
  MOTION_YSCROLL: "y scroll",
  MOTION_STAGE_SELECTED: "Stage selected: no motion blocks",
  OPERATORS_ADD: "%1 + %2",
  OPERATORS_SUBTRACT: "%1 - %2",
  OPERATORS_MULTIPLY: "%1 * %2",
  OPERATORS_DIVIDE: "%1 / %2",
  OPERATORS_RANDOM: "pick random %1 to %2",
  OPERATORS_GT: "%1 > %2",
  OPERATORS_LT: "%1 < %2",
  OPERATORS_EQUALS: "%1 = %2",
  OPERATORS_AND: "%1 and %2",
  OPERATORS_OR: "%1 or %2",
  OPERATORS_NOT: "not %1",
  OPERATORS_JOIN: "join %1 %2",
  OPERATORS_JOIN_APPLE: "apple",
  OPERATORS_JOIN_BANANA: "banana",
  OPERATORS_LETTEROF: "letter %1 of %2",
  OPERATORS_LETTEROF_APPLE: "a",
  OPERATORS_LENGTH: "length of %1",
  OPERATORS_CONTAINS: "%1 contains %2?",
  OPERATORS_MOD: "%1 mod %2",
  OPERATORS_ROUND: "round %1",
  OPERATORS_MATHOP: "%1 of %2",
  OPERATORS_MATHOP_ABS: "abs",
  OPERATORS_MATHOP_FLOOR: "floor",
  OPERATORS_MATHOP_CEILING: "ceiling",
  OPERATORS_MATHOP_SQRT: "sqrt",
  OPERATORS_MATHOP_SIN: "sin",
  OPERATORS_MATHOP_COS: "cos",
  OPERATORS_MATHOP_TAN: "tan",
  OPERATORS_MATHOP_ASIN: "asin",
  OPERATORS_MATHOP_ACOS: "acos",
  OPERATORS_MATHOP_ATAN: "atan",
  OPERATORS_MATHOP_LN: "ln",
  OPERATORS_MATHOP_LOG: "log",
  OPERATORS_MATHOP_EEXP: "e ^",
  OPERATORS_MATHOP_10EXP: "10 ^",
  PROCEDURES_DEFINITION: "define %1",
  SENSING_TOUCHINGOBJECT: "touching %1?",
  SENSING_TOUCHINGOBJECT_POINTER: "mouse-pointer",
  SENSING_TOUCHINGOBJECT_EDGE: "edge",
  SENSING_TOUCHINGCOLOR: "touching color %1?",
  SENSING_COLORISTOUCHINGCOLOR: "color %1 is touching %2?",
  SENSING_DISTANCETO: "distance to %1",
  SENSING_DISTANCETO_POINTER: "mouse-pointer",
  SENSING_ASKANDWAIT: "ask %1 and wait",
  SENSING_ASK_TEXT: "What's your name?",
  SENSING_ANSWER: "answer",
  SENSING_KEYPRESSED: "key %1 pressed?",
  SENSING_MOUSEDOWN: "mouse down?",
  SENSING_MOUSEX: "mouse x",
  SENSING_MOUSEY: "mouse y",
  SENSING_SETDRAGMODE: "set drag mode %1",
  SENSING_SETDRAGMODE_DRAGGABLE: "draggable",
  SENSING_SETDRAGMODE_NOTDRAGGABLE: "not draggable",
  SENSING_LOUDNESS: "loudness",
  SENSING_LOUD: "loud?",
  SENSING_TIMER: "timer",
  SENSING_RESETTIMER: "reset timer",
  SENSING_OF: "%1 of %2",
  SENSING_OF_XPOSITION: "x position",
  SENSING_OF_YPOSITION: "y position",
  SENSING_OF_DIRECTION: "direction",
  SENSING_OF_COSTUMENUMBER: "costume #",
  SENSING_OF_COSTUMENAME: "costume name",
  SENSING_OF_SIZE: "size",
  SENSING_OF_VOLUME: "volume",
  SENSING_OF_BACKDROPNUMBER: "backdrop #",
  SENSING_OF_BACKDROPNAME: "backdrop name",
  SENSING_OF_STAGE: "Stage",
  SENSING_CURRENT: "current %1",
  SENSING_CURRENT_YEAR: "year",
  SENSING_CURRENT_MONTH: "month",
  SENSING_CURRENT_DATE: "date",
  SENSING_CURRENT_DAYOFWEEK: "day of week",
  SENSING_CURRENT_HOUR: "hour",
  SENSING_CURRENT_MINUTE: "minute",
  SENSING_CURRENT_SECOND: "second",
  SENSING_DAYSSINCE2000: "days since 2000",
  SENSING_USERNAME: "username",
  SENSING_USERID: "user id",
  SOUND_PLAY: "start sound %1",
  SOUND_PLAYUNTILDONE: "play sound %1 until done",
  SOUND_STOPALLSOUNDS: "stop all sounds",
  SOUND_SETEFFECTO: "set %1 effect to %2",
  SOUND_CHANGEEFFECTBY: "change %1 effect by %2",
  SOUND_CLEAREFFECTS: "clear sound effects",
  SOUND_EFFECTS_PITCH: "pitch",
  SOUND_EFFECTS_PAN: "pan left/right",
  SOUND_CHANGEVOLUMEBY: "change volume by %1",
  SOUND_SETVOLUMETO: "set volume to %1%",
  SOUND_VOLUME: "volume",
  SOUND_RECORD: "record...",
  CATEGORY_MOTION: "Motion",
  CATEGORY_LOOKS: "Looks",
  CATEGORY_SOUND: "Sound",
  CATEGORY_EVENTS: "Events",
  CATEGORY_CONTROL: "Control",
  CATEGORY_SENSING: "Sensing",
  CATEGORY_OPERATORS: "Operators",
  CATEGORY_VARIABLES: "Variables",
  CATEGORY_MYBLOCKS: "My Blocks",
  COPY: "Copy",
  PASTE: "Paste",
  DUPLICATE: "Duplicate",
  DELETE: "Delete",
  ADD_COMMENT: "Add Comment",
  REMOVE_COMMENT: "Remove Comment",
  DELETE_BLOCK: "Delete Block",
  DELETE_X_BLOCKS: "Delete %1 Blocks",
  DELETE_ALL_BLOCKS: "Delete all %1 blocks?",
  CLEAN_UP: "Clean up Blocks",
  HELP: "Help",
  UNDO: "Undo",
  REDO: "Redo",
  EDIT_PROCEDURE: "Edit",
  SHOW_PROCEDURE_DEFINITION: "Go to definition",
  WORKSPACE_COMMENT_DEFAULT_TEXT: "Say something...",
  COLOUR_HUE_LABEL: "Color",
  COLOUR_SATURATION_LABEL: "Saturation",
  COLOUR_BRIGHTNESS_LABEL: "Brightness",
  CHANGE_VALUE_TITLE: "Change value:",
  RENAME_VARIABLE: "Rename variable",
  RENAME_VARIABLE_TITLE: 'Rename all "%1" variables to:',
  RENAME_VARIABLE_MODAL_TITLE: "Rename Variable",
  NEW_VARIABLE: "Make a Variable",
  NEW_VARIABLE_TITLE: "New variable name:",
  VARIABLE_MODAL_TITLE: "New Variable",
  VARIABLE_ALREADY_EXISTS: 'A variable named "%1" already exists.',
  VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE:
    'A variable named "%1" already exists for another variable of type "%2".',
  DELETE_VARIABLE_CONFIRMATION: 'Delete %1 uses of the "%2" variable?',
  CANNOT_DELETE_VARIABLE_PROCEDURE:
    'Can\'t delete the variable "%1" because it\'s part of the definition of the function "%2"',
  DELETE_VARIABLE: 'Delete the "%1" variable',
  NEW_PROCEDURE: "Make a Block",
  PROCEDURE_ALREADY_EXISTS: 'A procedure named "%1" already exists.',
  PROCEDURE_DEFAULT_NAME: "block name",
  PROCEDURE_USED:
    "To delete a block definition, first remove all uses of the block",
  NEW_LIST: "Make a List",
  NEW_LIST_TITLE: "New list name:",
  LIST_MODAL_TITLE: "New List",
  LIST_ALREADY_EXISTS: 'A list named "%1" already exists.',
  RENAME_LIST_TITLE: 'Rename all "%1" lists to:',
  RENAME_LIST_MODAL_TITLE: "Rename List",
  DEFAULT_LIST_ITEM: "thing",
  DELETE_LIST: 'Delete the "%1" list',
  RENAME_LIST: "Rename list",
  NEW_BROADCAST_MESSAGE: "New message",
  NEW_BROADCAST_MESSAGE_TITLE: "New message name:",
  BROADCAST_MODAL_TITLE: "New Message",
  DEFAULT_BROADCAST_MESSAGE_NAME: "message1",
};

Blockly.ScratchMsgs.locales["hi"] = {
  CONTROL_FOREVER: "हमेशा",
  CONTROL_REPEAT: "दोहराएं %1",
  CONTROL_IF: "यदि %1 तो",
  CONTROL_ELSE: "अन्यथा",
  CONTROL_STOP: "रुकें",
  CONTROL_STOP_ALL: "सभी",
  CONTROL_STOP_THIS: "इस स्क्रिप्ट",
  CONTROL_STOP_OTHER: "स्प्राइट में अन्य स्क्रिप्ट",
  CONTROL_WAIT: "प्रतीक्षा करें %1 सेकंड",
  CONTROL_WAITUNTIL: "प्रतीक्षा करें जब तक %1",
  CONTROL_REPEATUNTIL: "दोहराएं जब तक %1",
  CONTROL_WHILE: "जब तक %1",
  CONTROL_FOREACH: "हर एक %1 में %2 के लिए",
  CONTROL_STARTASCLONE: "जब मैं एक क्लोन के रूप में शुरू होता हूँ",
  CONTROL_CREATECLONEOF: "%1 का क्लोन बनाएं",
  CONTROL_CREATECLONEOF_MYSELF: "मैं स्वयं",
  CONTROL_DELETETHISCLONE: "इस क्लोन को हटाएं",
  CONTROL_COUNTER: "गिनती",
  CONTROL_INCRCOUNTER: "गिनती बढ़ाएं",
  CONTROL_CLEARCOUNTER: "गिनती साफ़ करें",
  CONTROL_ALLATONCE: "सभी एक साथ",
  DATA_SETVARIABLETO: "%1 को सेट करें %2 के रूप में",
  DATA_CHANGEVARIABLEBY: "%1 को बदलें %2 के रूप में",
  DATA_SHOWVARIABLE: "%1 दिखाएं",
  DATA_HIDEVARIABLE: "%1 छुपाएं",
  DATA_ADDTOLIST: "%1 को जोड़ें %2 में",
  DATA_DELETEOFLIST: "%2 की %1 हटाएं",
  DATA_DELETEALLOFLIST: "%1 को पूरी तरह हटाएं",
  DATA_INSERTATLIST: "%1 को %3 के %2 पर डालें",
  DATA_REPLACEITEMOFLIST: "%2 के %1 को %3 के साथ बदलें",
  DATA_ITEMOFLIST: "%2 का %1 आइटम",
  DATA_ITEMNUMOFLIST: "%2 में %1 का आइटम #",
  DATA_LENGTHOFLIST: "%1 की लंबाई",
  DATA_LISTCONTAINSITEM: "%1 में %2 है?",
  DATA_SHOWLIST: "%1 दिखाएं",
  DATA_HIDELIST: "%1 छुपाएं",
  DATA_INDEX_ALL: "सभी",
  DATA_INDEX_LAST: "आखिरी",
  DATA_INDEX_RANDOM: "रैंडम",
  EVENT_WHENARDUINOBEGIN: "जब आर्डुइनो शुरू हो",
  EVENT_WHENMICROPYTHONBEGIN: "जब MicroPython शुरू हो",
  EVENT_WHENMICROBITBEGIN: "जब Microbit शुरू हो",
  EVENT_WHENMICROBITBUTTONPRESSED: "जब बटन %1 दबाया जाता है",
  EVENT_WHENMICROBITPINBEINGTOUCHED: "जब पिन %1 छूआ जा रहा है",
  EVENT_WHENMICROBITGESTURE: "जब इस चिन्ह %1",
  EVENT_WHENFLAGCLICKED: "जब %1 को क्लिक किया जाता है",
  EVENT_WHENTHISSPRITECLICKED: "जब इस स्प्राइट पर क्लिक किया जाता है",
  EVENT_WHENSTAGECLICKED: "जब स्टेज पर क्लिक किया जाता है",
  EVENT_WHENTOUCHINGOBJECT: "जब यह स्प्राइट %1 को छूता है",
  EVENT_WHENBROADCASTRECEIVED: "जब मैं %1 प्राप्त करता हूँ",
  EVENT_WHENBACKDROPSWITCHESTO: "जब बैकड्रॉप %1 पर स्विच होता है",
  EVENT_WHENGREATERTHAN: "जब %1 > %2",
  EVENT_WHENGREATERTHAN_TIMER: "टाइमर",
  EVENT_WHENGREATERTHAN_LOUDNESS: "ध्वनि",
  EVENT_BROADCAST: "प्रसारित करें %1",
  EVENT_BROADCASTANDWAIT: "प्रसारित करें %1 और प्रतीक्षा करें",
  EVENT_WHENKEYPRESSED: "जब %1 कुंजी दबाई जाती है",
  EVENT_WHENMICROBITGESTURE_SHAKEN: "हिलाया जाता है",
  EVENT_WHENMICROBITGESTURE_TILTEDUPWARD: "ऊपर की ओर झुकाया गया है",
  EVENT_WHENMICROBITGESTURE_TILTEDDOWNWARD: "नीचे की ओर झुकाया गया है",
  EVENT_WHENMICROBITGESTURE_TILTEDDLEFTWARD: "बाएं की ओर झुकाया गया है",
  EVENT_WHENMICROBITGESTURE_TILTEDDRIGHTWARD: "दाएं की ओर झुकाया गया है",
  EVENT_WHENMICROBITGESTURE_FACEUP: "उपर की ओर रहता है",
  EVENT_WHENMICROBITGESTURE_FACEDOWN: "नीचे की ओर रहता है",
  EVENT_WHENMICROBITGESTURE_FREEFALL: "गिरावट",
  EVENT_WHENKEYPRESSED_SPACE: "स्पेस",
  EVENT_WHENKEYPRESSED_LEFT: "बाएं तीर",
  EVENT_WHENKEYPRESSED_RIGHT: "दाएं तीर",
  EVENT_WHENKEYPRESSED_DOWN: "नीचे तीर",
  EVENT_WHENKEYPRESSED_UP: "ऊपर तीर",
  EVENT_WHENKEYPRESSED_ANY: "कोई भी",
  LOOKS_SAYFORSECS: "%1 कहो %2 सेकंड के लिए",
  LOOKS_SAY: "%1 कहो",
  LOOKS_HELLO: "नमस्ते!",
  LOOKS_THINKFORSECS: "%1 सोचो %2 सेकंड के लिए",
  LOOKS_THINK: "%1 सोचो",
  LOOKS_HMM: "हम्म...",
  LOOKS_SHOW: "दिखाएं",
  LOOKS_HIDE: "छुपाएं",
  LOOKS_HIDEALLSPRITES: "सभी स्प्राइट्स को छुपाएं",
  LOOKS_EFFECT_COLOR: "रंग",
  LOOKS_EFFECT_FISHEYE: "फिश आई",
  LOOKS_EFFECT_WHIRL: "घूमना",
  LOOKS_EFFECT_PIXELATE: "पिक्सलेट",
  LOOKS_EFFECT_MOSAIC: "मोजेक",
  LOOKS_EFFECT_BRIGHTNESS: "तेजी",
  LOOKS_EFFECT_GHOST: "भूत",
  LOOKS_CHANGEEFFECTBY: "परिणाम बदलें %1 द्वारा %2 के रूप में",
  LOOKS_SETEFFECTTO: "परिणाम सेट करें %1 को %2 के रूप में",
  LOOKS_CLEARGRAPHICEFFECTS: "सभी ग्राफिक परिणाम साफ़ करें",
  LOOKS_CHANGESIZEBY: "आकार बदलें %1 द्वारा",
  LOOKS_SETSIZETO: "आकार सेट करें %1 % के रूप में",
  LOOKS_SIZE: "आकार",
  LOOKS_CHANGESTRETCHBY: "स्ट्रेच बदलें %1 द्वारा",
  LOOKS_SETSTRETCHTO: "स्ट्रेच सेट करें %1 % के रूप में",
  LOOKS_SWITCHCOSTUMETO: "कॉस्ट्यूम स्विच करें %1 को",
  LOOKS_NEXTCOSTUME: "अगला कॉस्ट्यूम",
  LOOKS_SWITCHBACKDROPTO: "बैकड्रॉप स्विच करें %1 को",
  LOOKS_GOTOFRONTBACK: "जाएं %1 परत",
  LOOKS_GOFORWARDBACKWARDLAYERS: "जाएं %1 %2 परतें",
  LOOKS_BACKDROPNUMBERNAME: "बैकड्रॉप %1",
  LOOKS_COSTUMENUMBERNAME: "कॉस्ट्यूम %1",
  LOOKS_NUMBERNAME_NUMBER: "नंबर",
  LOOKS_NUMBERNAME_NAME: "नाम",
  LOOKS_SWITCHBACKDROPTOANDWAIT: "बैकड्रॉप को बदलें %1 और प्रतीक्षा करें",
  LOOKS_NEXTBACKDROP_BLOCK: "अगला बैकड्रॉप",
  LOOKS_NEXTBACKDROP: "अगला बैकड्रॉप",
  LOOKS_PREVIOUSBACKDROP: "पिछला बैकड्रॉप",
  LOOKS_RANDOMBACKDROP: "रैंडम बैकड्रॉप",
  MOTION_MOVESTEPS: "चलें %1 कदम",
  MOTION_TURNLEFT: "मुड़ें %1 %2 डिग्री",
  MOTION_TURNRIGHT: "मुड़ें %1 %2 डिग्री",
  MOTION_POINTINDIRECTION: "दिशा में इंगीत करें %1",
  MOTION_POINTTOWARDS: "की ओर इंगीत करें %1",
  MOTION_POINTTOWARDS_POINTER: "माउस पॉइंटर",
  MOTION_POINTTOWARDS_RANDOM: "रैंडम दिशा",
  MOTION_GOTO: "जाएं %1",
  MOTION_GOTO_POINTER: "माउस पॉइंटर",
  MOTION_GOTO_RANDOM: "रैंडम स्थान",
  MOTION_GOTOXY: "जाएं x: %1 y: %2",
  MOTION_GLIDESECSTOXY: "स्लाइड %1 सेकंड्स में x: %2 y: %3",
  MOTION_GLIDETO: "स्लाइड %1 सेकंड्स में %2",
  MOTION_GLIDETO_POINTER: "माउस पॉइंटर",
  MOTION_GLIDETO_RANDOM: "रैंडम स्थान",
  MOTION_CHANGEXBY: "x को बदलें %1",
  MOTION_SETX: "x को सेट करें %1",
  MOTION_CHANGEYBY: "y को बदलें %1",
  MOTION_SETY: "y को सेट करें %1",
  MOTION_IFONEDGEBOUNCE: "अगर किनारे पर है, उछलो",
  MOTION_SETROTATIONSTYLE: "घूमने की शैली सेट करें %1",
  MOTION_SETROTATIONSTYLE_LEFTRIGHT: "बाएं-दाएं",
  MOTION_SETROTATIONSTYLE_DONTROTATE: "घूमाएं नहीं",
  MOTION_SETROTATIONSTYLE_ALLAROUND: "सभी दिशाओं में",
  MOTION_XPOSITION: "x स्थिति",
  MOTION_YPOSITION: "y स्थिति",
  MOTION_DIRECTION: "दिशा",
  MOTION_SCROLLRIGHT: "दाएं स्क्रॉल %1",
  MOTION_SCROLLUP: "ऊपर स्क्रॉल %1",
  MOTION_ALIGNSCENE: "सीन को सारें %1 करें",
  MOTION_ALIGNSCENE_BOTTOMLEFT: "नीचे-बाएं",
  MOTION_ALIGNSCENE_BOTTOMRIGHT: "नीचे-दाएं",
  MOTION_ALIGNSCENE_MIDDLE: "मध्य",
  MOTION_ALIGNSCENE_TOPLEFT: "ऊपर-बाएं",
  MOTION_ALIGNSCENE_TOPRIGHT: "ऊपर-दाएं",
  MOTION_XSCROLL: "x स्क्रॉल",
  MOTION_YSCROLL: "y स्क्रॉल",
  MOTION_STAGE_SELECTED: "स्टेज चयनित: कोई मोशन ब्लॉक नहीं",
  OPERATORS_ADD: "%1 + %2",
  OPERATORS_SUBTRACT: "%1 - %2",
  OPERATORS_MULTIPLY: "%1 * %2",
  OPERATORS_DIVIDE: "%1 / %2",
  OPERATORS_RANDOM: "रैंडम %1 से %2 तक चुनें",
  OPERATORS_GT: "%1 > %2",
  OPERATORS_LT: "%1 < %2",
  OPERATORS_EQUALS: "%1 = %2",
  OPERATORS_AND: "%1 और %2",
  OPERATORS_OR: "%1 या %2",
  OPERATORS_NOT: "नहीं %1",
  OPERATORS_JOIN: "%1 और %2 जोड़ें",
  OPERATORS_JOIN_APPLE: "सेब",
  OPERATORS_JOIN_BANANA: "केला",
  OPERATORS_LETTEROF: "%2 का अक्षर %1",
  OPERATORS_LETTEROF_APPLE: "ए",
  OPERATORS_LENGTH: "%1 की लंबाई",
  OPERATORS_CONTAINS: "%1 में %2 है?",
  OPERATORS_MOD: "%1 मॉड %2",
  OPERATORS_ROUND: "%1 का राउंड ऑफ",
  OPERATORS_MATHOP: "%2 का %1",
  OPERATORS_MATHOP_ABS: "एब्स",
  OPERATORS_MATHOP_FLOOR: "फ्लोर",
  OPERATORS_MATHOP_CEILING: "सीलिंग",
  OPERATORS_MATHOP_SQRT: "वर्गमूल",
  OPERATORS_MATHOP_SIN: "साइन",
  OPERATORS_MATHOP_COS: "कोस",
  OPERATORS_MATHOP_TAN: "टैन",
  OPERATORS_MATHOP_ASIN: "एसिन",
  OPERATORS_MATHOP_ACOS: "एकॉस",
  OPERATORS_MATHOP_ATAN: "एटैन",
  OPERATORS_MATHOP_LN: "ln",
  OPERATORS_MATHOP_LOG: "लॉग",
  OPERATORS_MATHOP_EEXP: "e ^",
  OPERATORS_MATHOP_10EXP: "10 ^",
  PROCEDURES_DEFINITION: "%1 की परिभाषा करें",
  SENSING_TOUCHINGOBJECT: "%1 को छू रहा है?",
  SENSING_TOUCHINGOBJECT_POINTER: "माउस पॉइंटर",
  SENSING_TOUCHINGOBJECT_EDGE: "किनारा",
  SENSING_TOUCHINGCOLOR: "रंग %1 को छू रहा है?",
  SENSING_COLORISTOUCHINGCOLOR: "रंग %1 %2 को छू रहा है?",
  SENSING_DISTANCETO: "%1 की दूरी",
  SENSING_DISTANCETO_POINTER: "माउस पॉइंटर",
  SENSING_ASKANDWAIT: "%1 पूछें और प्रतीक्षा करें",
  SENSING_ASK_TEXT: "आपका नाम क्या है?",
  SENSING_ANSWER: "उत्तर",
  SENSING_KEYPRESSED: "कुंजी %1 दबाई गई है?",
  SENSING_MOUSEDOWN: "माउस नीचे है?",
  SENSING_MOUSEX: "माउस x",
  SENSING_MOUSEY: "माउस y",
  SENSING_SETDRAGMODE: "ड्रैग मोड सेट करें %1",
  SENSING_SETDRAGMODE_DRAGGABLE: "ड्रैगेबल",
  SENSING_SETDRAGMODE_NOTDRAGGABLE: "ड्रैगेबल नहीं",
  SENSING_LOUDNESS: "ध्वनि मात्रा",
  SENSING_LOUD: "ध्वनि?",
  SENSING_TIMER: "टाइमर",
  SENSING_RESETTIMER: "टाइमर रीसेट करें",
  SENSING_OF: "%1 का %2",
  SENSING_OF_XPOSITION: "x स्थान",
  SENSING_OF_YPOSITION: "y स्थान",
  SENSING_OF_DIRECTION: "दिशा",
  SENSING_OF_COSTUMENUMBER: "कॉस्ट्यूम नंबर",
  SENSING_OF_COSTUMENAME: "कॉस्ट्यूम नाम",
  SENSING_OF_SIZE: "आकार",
  SENSING_OF_VOLUME: "वॉल्यूम",
  SENSING_OF_BACKDROPNUMBER: "बैकड्रॉप नंबर",
  SENSING_OF_BACKDROPNAME: "बैकड्रॉप नाम",
  SENSING_OF_STAGE: "स्टेज",
  SENSING_CURRENT: "वर्तमान %1",
  SENSING_CURRENT_YEAR: "वर्ष",
  SENSING_CURRENT_MONTH: "महीना",
  SENSING_CURRENT_DATE: "तारीख",
  SENSING_CURRENT_DAYOFWEEK: "सप्ताह का दिन",
  SENSING_CURRENT_HOUR: "घंटा",
  SENSING_CURRENT_MINUTE: "मिनट",
  SENSING_CURRENT_SECOND: "सेकंड",
  SENSING_DAYSSINCE2000: "2000 के बाद के दिन",
  SENSING_USERNAME: "उपयोगकर्ता नाम",
  SENSING_USERID: "उपयोगकर्ता आईडी",
  SOUND_PLAY: "ध्वनि चालाएं %1",
  SOUND_PLAYUNTILDONE: "ध्वनि चलाएं %1 जब तक समाप्त नहीं होता",
  SOUND_STOPALLSOUNDS: "सभी ध्वनियों को रोकें",
  SOUND_SETEFFECTO: "%1 प्रभाव सेट करें %2",
  SOUND_CHANGEEFFECTBY: "%1 प्रभाव को बदलें %2",
  SOUND_CLEAREFFECTS: "सभी ध्वनि प्रभाव साफ़ करें",
  SOUND_EFFECTS_PITCH: "पिच",
  SOUND_EFFECTS_PAN: "बाएं/दाएं पैन",
  SOUND_CHANGEVOLUMEBY: "ध्वनि को बदलें %1 के द्वारा",
  SOUND_SETVOLUMETO: "वॉल्यूम सेट करें %1%",
  SOUND_VOLUME: "वॉल्यूम",
  SOUND_RECORD: "रिकॉर्ड...",
  CATEGORY_MOTION: "गति",
  CATEGORY_LOOKS: "दिखावट",
  CATEGORY_SOUND: "ध्वनि",
  CATEGORY_EVENTS: "घटनाएं",
  CATEGORY_CONTROL: "नियंत्रण",
  CATEGORY_SENSING: "संवेदना",
  CATEGORY_OPERATORS: "ऑपरेटर्स",
  CATEGORY_VARIABLES: "चर",
  CATEGORY_MYBLOCKS: "मेरे ब्लॉक्स",
  COPY: "कॉपी",
  PASTE: "पेस्ट",
  DUPLICATE: "प्रतिलिपि बनाएं",
  DELETE: "हटाएं",
  ADD_COMMENT: "टिप्पणी जोड़ें",
  REMOVE_COMMENT: "टिप्पणी हटाएं",
  DELETE_BLOCK: "ब्लॉक हटाएं",
  DELETE_X_BLOCKS: " %1 ब्लॉक्स हटाएं",
  DELETE_ALL_BLOCKS: "क्या आप सभी %1 ब्लॉक्स को हटाना चाहते हैं?",
  CLEAN_UP: "ब्लॉक्स साफ करें",
  HELP: "सहायता",
  UNDO: "पूर्ववत करें",
  REDO: "फिर से करें",
  EDIT_PROCEDURE: "संपादन करें",
  SHOW_PROCEDURE_DEFINITION: "परिभाषा पर जाएं",
  WORKSPACE_COMMENT_DEFAULT_TEXT: "कुछ कहें...",
  COLOUR_HUE_LABEL: "रंग",
  COLOUR_SATURATION_LABEL: "उदासीनता",
  COLOUR_BRIGHTNESS_LABEL: "चमक",
  CHANGE_VALUE_TITLE: "मूल्य बदलें:",
  RENAME_VARIABLE: "मान का नाम बदलें",
  RENAME_VARIABLE_TITLE: 'सभी "%1" मानों का नाम बदलें:',
  RENAME_VARIABLE_MODAL_TITLE: "मान का नाम बदलें",
  NEW_VARIABLE: "मान बनाएं",
  NEW_VARIABLE_TITLE: "नया मान नाम:",
  VARIABLE_MODAL_TITLE: "नया मान",
  VARIABLE_ALREADY_EXISTS: ' "%1" नामक मान पहले से मौजूद है।',
  VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE:
    '"%1" नामक मान पहले से ही "%2" प्रकार की दूसरी मान के लिए मौजूद है।',
  DELETE_VARIABLE_CONFIRMATION: '"%2" मान के %1 उपयोगों को हटाएं?',
  CANNOT_DELETE_VARIABLE_PROCEDURE:
    '"%2" फ़ंक्शन के परिभाषा का हिस्सा है क्योंकि "%1" मान को हटा नहीं सकते',
  DELETE_VARIABLE: '"%1" मान को हटाएं',
  NEW_PROCEDURE: "ब्लॉक बनाएं",
  PROCEDURE_ALREADY_EXISTS: '"%1" नामक ब्लॉक पहले से मौजूद है।',
  PROCEDURE_DEFAULT_NAME: "ब्लॉक का नाम",
  PROCEDURE_USED:
    "एक ब्लॉक परिभाषा को हटाने के लिए, पहले ब्लॉक के सभी उपयोगों को हटाएं",
  NEW_LIST: "सूची बनाएं",
  NEW_LIST_TITLE: "नई सूची का नाम:",
  LIST_MODAL_TITLE: "नई सूची",
  LIST_ALREADY_EXISTS: '"%1" नामक सूची पहले से मौजूद है।',
  RENAME_LIST_TITLE: 'सभी "%1" सूचियों को नाम बदलें:',
  RENAME_LIST_MODAL_TITLE: "सूची का नाम बदलें",
  DEFAULT_LIST_ITEM: "वस्तु",
  DELETE_LIST: '"%1" सूची को हटाएं',
  RENAME_LIST: "सूची का नाम बदलें",
  NEW_BROADCAST_MESSAGE: "नई संदेश",
  NEW_BROADCAST_MESSAGE_TITLE: "नए संदेश का नाम:",
  BROADCAST_MODAL_TITLE: "नया संदेश",
  DEFAULT_BROADCAST_MESSAGE_NAME: "संदेश1",
};

// End of combined translations
